config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/sidekiq"

  namespace :api, defaults: { format: :json } do
    resource :game_session

    resources :levels
    resources :submissions, only: [:create, :show]

    resource :ping, only: [:show]
  end

  namespace :statistics do
    resources :submissions

    root to: "dashboard#show"
  end

  root to: "menu#show"
  get "/game", to: "game#show"
  get "/summary", to: "summary#show"
  post "/summary", to: "summary#update"
  get "/credits", to: "credits#show"
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :level
  has_many :messages

  validates :name, presence: true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :messages, -> { order(position: :asc) }
  belongs_to :level
end

app/models/game_session.rb
class GameSession < ActiveRecord::Base
  has_many :submissions
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,if: ->(model) { model.email.present? }

  scope :finished, -> { where.not(email: nil) }
end

app/models/level.rb
class Level < ActiveRecord::Base
  default_scope { order(position: :asc) }

  has_many :submissions
  has_many :characters
  has_one :conversation
  has_one :task

  validates :position, presence: true
  validates :position, uniqueness: true

  acts_as_list
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :character
  belongs_to :conversation

  validates :content, presence: true
  validates :position, uniqueness: { scope: :conversation_id }

  acts_as_list scope: :conversation
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :level
  belongs_to :game_session

  enum status: [:pending, :failed, :succeed]

  validates :content, presence: true

  scope :correct, -> { where(status: 2) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :level

  validates :content, presence: true
  validates :points, presence: true
  validates :test_class, presence: true
end

app/controllers/api/base_controller.rb
class API::BaseController < ApplicationController
  include LevelAuthorization
  include SubmissionAuthorization

  protect_from_forgery with: :null_session
end

app/controllers/api/game_sessions_controller.rb
class API::GameSessionsController < API::BaseController
  def show
    render json: current_session
  end
end

app/controllers/api/levels_controller.rb
class API::LevelsController < API::BaseController
  def index
    render json: Level.all, each_serializer: LevelBaseSerializer, status: :ok
  end

  def show
    authorize_level! level_number

    @level = Level.find level_number

    render json: @level, status: :ok
  end

  private

  def level_number
    params[:id]
  end
end

app/controllers/api/pings_controller.rb
class API::PingsController < API::BaseController
  def index
    render json: { message: "Pong!" }, status: 200
  end
end

app/controllers/api/submissions_controller.rb
class API::SubmissionsController < API::BaseController
  before_action :set_submission, only: :show

  def show
    authorize_submission! @submission

    render json: @submission
  end

  def create
    authorize_level! level_number

    @submission = Submission.new submission_params
    @submission.game_session = current_session

    if @submission.save
      enqueue_submission_verification @submission
      render json: @submission
    else
      render json: { errors: @submission.errors }, status: :unprocessable_entity
    end
  end

  private

  def enqueue_submission_verification(submission)
    SubmissionVerifierJob.perform_later submission.id
  end

  def set_submission
    @submission = Submission.find params[:id]
  end

  def level_number
    submission_params[:level_id]
  end

  def submission_params
    params.require(:submission).permit :content, :level_id
  end
end

app/controllers/api/v1/pings_controller.rb
class API::V1::PingsController < API::V1::BaseController
  def index
    render json: { message: "Pong!" }, status: 200
  end
end

app/controllers/api/v1/submissions_controller.rb
class SubmissionsController < API::V1::BaseController
  before_action :set_submission, only: :show

  def show
    render json: @submission
  end

  def create
    @submission = Submission.new submission_params

    if @submission.save
      render json: @submission
    else
      render json: { errors: @submission.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_submission
    @submission = Submission.find params[:id]
  end

  def submission_params
    params.require(:submission).permit :content
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_session
    @current_session ||= authenticator.authenticate_game_sassion
  end

  def authenticator
    GameSessionAuthenticator.new cookies, request
  end
end

app/controllers/concerns/level_authorization.rb
module LevelAuthorization
  extend ActiveSupport::Concern

  included do
    rescue_from LevelAuthorizer::LevelUnauthorized do
      head status: :unauthorized
    end
  end

  def authorize_level!(level_number)
    level_authorizer.authorize! level_number
  end

  def level_authorizer
    @level_authorizer ||= LevelAuthorizer.new current_session
  end
end

app/controllers/concerns/submission_authorization.rb
module SubmissionAuthorization
  extend ActiveSupport::Concern

  included do
    rescue_from SubmissionAuthorizer::SubmissionUnauthorized do
      head status: :unauthorized
    end
  end

  def authorize_submission!(submission)
    submission_authorizer.authorize! submission
  end

  def submission_authorizer
    @submission_authorizer ||= SubmissionAuthorizer.new current_session
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def show
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
    @current_level = current_session.current_level
  end
end

app/controllers/statistics/base_controller.rb
class Statistics::BaseController < ApplicationController
  http_basic_authenticate_with name: ENV["SIDEKIQ_USERNAME"], password: ENV["SIDEKIQ_PASSWORD"] if Rails.env.production?
end

app/controllers/statistics/dashboard_controller.rb
class Statistics::DashboardController < Statistics::BaseController
  def show
  end
end

app/controllers/statistics/submissions_controller.rb
class Statistics::SubmissionsController < Statistics::BaseController
  before_action :set_submission, only: :show

  def index
    submissions = Submission.correct.order("created_at DESC, id DESC, level_id DESC")

    @filter_form = SubmissionsFilterForm.new(submissions)

    @sessions = GameSession.finished
    @levels   = Level.all

    if params[:filter]
      submissions = @filter_form.submit(params[:filter])
    end

    @submissions = submissions
  end

  def show
  end

  private

  def set_submission
    @submission = Submission.find params[:id]
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def show
    if summary_authorizer.authorized?
      render :show
    else
      redirect_to root_path
    end
  end

  def update
    current_session.email = params[:email]
    if current_session.save
      @show_success = true
      render :show
    else
      @message = "Your email is not valid"
      render :show
    end
  end

  private

  def summary_authorizer
    @summary_authorizer = SummaryAuthorizer.new(current_session)
  end

  def authorized?
    summary_authorizer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end
end

app/views/statistics/submissions/index.html.haml
%h1
  Wyników:
  = @submissions.count

= form_for @filter_form, as: :filter, url: statistics_submissions_path, method: :get, html: { id: "filter-form" } do |f|
  .field
    = f.label :finished_game, "Wyniki dla graczy, którzy ukończyli grę"
    = f.check_box :finished_game
  .field
    = f.label :game_session_id, "Gracz"
    = f.select(:game_session_id,
      options_for_select(@sessions.map { |session| [session.email, session.id] },
      @filter_form.game_session_id), include_blank: "Wszystkie")
  .field
    = f.label :level_id, "Poziom"
    = f.select(:level_id,
      options_for_select(@levels.map { |level| ["Poziom #{level.id}", level.id] },
      @filter_form.level_id), include_blank: "Wszystkie")
  .field
    = f.submit "Szukaj", class: "ui button  floated right"
    = link_to "Wyczyść filtry", statistics_submissions_path, class: "ui button basic floated right"

%table
  %thead
    %tr
      %td{ style: "width:100px" } Id
      %td{ style: "width:300px" } Data
      %td{ style: "width:100px" } Gracz
      %td{ style: "width:100px" } Poziom
      %td{ style: "width:50%" } Odpowiedz
  %tbody
    - @submissions.each do |submission|
      %tr
        %td{ colspan: 5, class: "table-separator"}
      %tr{ id: submission.id }
        %td= link_to(submission.id, statistics_submission_path(submission))
        %td= submission.created_at
        %td= link_to(submission.game_session.email.presence || submission.game_session.cookie_key, statistics_submissions_path(params: { filter: { game_session_id: submission.game_session_id } }))
        %td= link_to(submission.level_id, statistics_submissions_path(params: { filter: { level_id: submission.level_id } }))
        %td
          %textarea{ style: "width: 600px;height:300px" }= submission.content

app/views/statistics/submissions/show.html.haml
%table
  %tr
    %td Id
    %td= link_to(@submission.id, statistics_submission_path(@submission))
  %tr
    %td Status
    %td= @submission.status
  %tr
    %td Data
    %td= @submission.created_at
  %tr
    %td Gracz
    %td= @submission.game_session.email.presence || @submission.game_session.cookie_key
  %tr
    %td Poziom
    %td= @submission.level_id
  %tr
    %td Odpowiedz
    %td
      %textarea{ style: "width: 600px;height:300px" }= @submission.content