config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/sidekiq"

  namespace :api, defaults: { format: :json } do
    resource :game_session

    resources :levels
    resources :submissions, only: [:create, :show]

    resource :ping, only: [:show]
  end

  namespace :statistics do
    resources :submissions

    root to: "dashboard#show"
  end

  root to: "menu#show"
  get "/game", to: "game#show"
  get "/summary", to: "summary#show"
  post "/summary", to: "summary#update"
  get "/credits", to: "credits#show"
end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :level
  has_many :messages

  validates :name, presence: true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  has_many :messages, -> { order(position: :asc) }
  belongs_to :level
end

app/models/game_session.rb
class GameSession < ActiveRecord::Base
  has_many :submissions
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/,if: ->(model) { model.email.present? }

  scope :finished, -> { where.not(email: nil) }
end

app/models/level.rb
class Level < ActiveRecord::Base
  default_scope { order(position: :asc) }

  has_many :submissions
  has_many :characters
  has_one :conversation
  has_one :task

  validates :position, presence: true
  validates :position, uniqueness: true

  acts_as_list
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :character
  belongs_to :conversation

  validates :content, presence: true
  validates :position, uniqueness: { scope: :conversation_id }

  acts_as_list scope: :conversation
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :level
  belongs_to :game_session

  enum status: [:pending, :failed, :succeed]

  validates :content, presence: true

  scope :correct, -> { where(status: 2) }
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :level

  validates :content, presence: true
  validates :points, presence: true
  validates :test_class, presence: true
end

app/controllers/api/base_controller.rb
class API::BaseController < ApplicationController
  include LevelAuthorization
  include SubmissionAuthorization

  protect_from_forgery with: :null_session
end

app/controllers/api/game_sessions_controller.rb
class API::GameSessionsController < API::BaseController
  def show
    render json: current_session
  end
end

app/controllers/api/levels_controller.rb
class API::LevelsController < API::BaseController
  def index
    render json: Level.all, each_serializer: LevelBaseSerializer, status: :ok
  end

  def show
    authorize_level! level_number

    @level = Level.find level_number

    render json: @level, status: :ok
  end

  private

  def level_number
    params[:id]
  end
end

app/controllers/api/pings_controller.rb
class API::PingsController < API::BaseController
  def index
    render json: { message: "Pong!" }, status: 200
  end
end

app/controllers/api/submissions_controller.rb
class API::SubmissionsController < API::BaseController
  before_action :set_submission, only: :show

  def show
    authorize_submission! @submission

    render json: @submission
  end

  def create
    authorize_level! level_number

    @submission = Submission.new submission_params
    @submission.game_session = current_session

    if @submission.save
      enqueue_submission_verification @submission
      render json: @submission
    else
      render json: { errors: @submission.errors }, status: :unprocessable_entity
    end
  end

  private

  def enqueue_submission_verification(submission)
    SubmissionVerifierJob.perform_later submission.id
  end

  def set_submission
    @submission = Submission.find params[:id]
  end

  def level_number
    submission_params[:level_id]
  end

  def submission_params
    params.require(:submission).permit :content, :level_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_session
    @current_session ||= authenticator.authenticate_game_sassion
  end

  def authenticator
    GameSessionAuthenticator.new cookies, request
  end
end

app/controllers/concerns/level_authorization.rb
module LevelAuthorization
  extend ActiveSupport::Concern

  included do
    rescue_from LevelAuthorizer::LevelUnauthorized do
      head status: :unauthorized
    end
  end

  def authorize_level!(level_number)
    level_authorizer.authorize! level_number
  end

  def level_authorizer
    @level_authorizer ||= LevelAuthorizer.new current_session
  end
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def show
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def show
  end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def show
    @current_level = current_session.current_level
  end
end

app/controllers/statistics/base_controller.rb
class Statistics::BaseController < ApplicationController
  http_basic_authenticate_with name: ENV["SIDEKIQ_USERNAME"], password: ENV["SIDEKIQ_PASSWORD"] if Rails.env.production?
end

app/controllers/statistics/dashboard_controller.rb
class Statistics::DashboardController < Statistics::BaseController
  def show
  end
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def show
    if summary_authorizer.authorized?
      render :show
    else
      redirect_to root_path
    end
  end

  def update
    current_session.email = params[:email]
    if current_session.save
      @show_success = true
      render :show
    else
      @message = "Your email is not valid"
      render :show
    end
  end

  private

  def summary_authorizer
    @summary_authorizer = SummaryAuthorizer.new(current_session)
  end

  def authorized?
    summary_authorizer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
  end
end

app/views/credits/show.html.haml
#game-wrap
  %svg{ id: "ui", width: "325.4px", height: "265.7px", viewbox: "0 0 325.4 265.7", opacity: 1, visibility: "visible" }
    %g{ id: "menu-trigger", class: "ui button" }
      %text{ style: "font-size:38px;", transform: "matrix(1 0 0 1 81.2697 39.7337)"} MENU
      %rect{ height: "5.5", style: "fill:#F78F1E;", width: "32.7", x: "23.8", y: "14.5"}
      %rect{ height: "5.5", style: "fill:#F15623;", width: "32.7", x: "23.8", y: "23.9"}
      %rect{ height: "5.5", style: "fill:#D44227;", width: "32.7", x: "23.8", y: "33.3"}

= embedded_svg "credits.svg"


:javascript
  $('g#menu-trigger').on('click', function() {
    window.location.href = '/';
  });

app/views/game/show.html.haml
#game-wrap

  %svg{ id: "ui", width: "325.4px", height: "265.7px", viewbox: "0 0 325.4 265.7", opacity: 0, visibility: "hidden" }
    %g{ visibility: "hidden" }
      %path{ d: "M39.3,60.2c0,0.2,0,0.4,0,0.7c-0.2,0-0.5,0-0.7,0c0-0.2,0-0.4,0-0.7c0-0.5,0-1-0.1-1.5\r\n\t\t\tc-2.8-10.3-5.6-20.5-8.4-30.8c6,0,12,0,18,0c-2.1,7.6-4.3,15.1-6.2,22.7C40.8,53.8,39.6,56.9,39.3,60.2z", style: "fill:#F05023;"}
      %path{ d: "M29.9,27.9c2.8,10.3,5.6,20.5,8.4,30.8c0.1,0.5,0.1,1,0.1,1.5c-3.6-4.9-7.2-9.8-10.8-14.7\r\n\t\t\tc-4.2-5.7-8.5-11.5-12.7-17.2c0-0.1,0-0.2,0-0.4C19.9,27.9,24.9,27.9,29.9,27.9L29.9,27.9z", style: "fill:#F2612F;"}
      %path{ d: "M39.3,60.2c0.3-3.3,1.5-6.4,2.3-9.5c2-7.6,4.1-15.1,6.2-22.7l0,0c5,0,10,0,15,0c0,0.1,0,0.2,0,0.4\r\n\t\t\tc-4.5,6.1-8.9,12.2-13.4,18.3C46,51.1,42.9,55.8,39.3,60.2z", style: "fill:#F2612F;"}
      %path{ d: "M47.8,27.9c-6,0-12,0-18,0l0,0c0-0.1,0-0.2,0-0.4c1.3-1.4,2.1-3.2,3-4.8c1.8-3.3,4.2-6.2,5.5-9.8\r\n\t\t\tc0.2,0,0.5,0,0.7,0c2.4,5.1,5.5,9.8,8.6,14.6C47.8,27.7,47.8,27.8,47.8,27.9L47.8,27.9z", style: "fill:#F2612F;"}
      %path{ d: "M47.8,27.6c-3-4.8-6.2-9.5-8.6-14.6c5.5,0,11,0,16.4,0c0,0.1-0.1,0.2-0.1,0.4\r\n\t\t\tc-0.9,0.2-0.9,1.1-1.3,1.7C52.1,19.2,50.3,23.5,47.8,27.6z", style: "fill:#D44227;"}
      %path{ d: "M38.5,13c-1.4,3.5-3.7,6.5-5.5,9.8c-0.9,1.7-1.8,3.4-3,4.8c-2.3-3.8-4.1-8-6.2-12\r\n\t\t\tc-0.4-0.8-0.6-1.8-1.5-2.3c0-0.1,0-0.2,0.2-0.3C27.8,13,33.1,13,38.5,13z", style: "fill:#D44227;"}
      %path{ d: "M22.3,13.3c0.9,0.5,1,1.5,1.5,2.3c2.1,4,3.8,8.1,6.2,12c0,0.1,0,0.2,0,0.4c-5,0-10,0-15,0\r\n\t\t\tc0-0.1,0-0.2,0-0.4C17.4,22.8,19.8,18,22.3,13.3z", style: "fill:#F05023;"}
      %path{ d: "M47.8,27.6c2.4-4,4.2-8.4,6.5-12.5c0.3-0.6,0.4-1.5,1.3-1.7c2.4,4.7,4.8,9.5,7.2,14.2\r\n\t\t\tc0,0.1,0,0.2,0,0.4c-5,0-10,0-15,0C47.8,27.8,47.8,27.7,47.8,27.6z", style: "fill:#F05023;"}
      %rect{ height: "37.5", style: "fill:none;", width: "64.4", x: "81.3", y: "17.5"}

      %text{ id: "score", style: "fill:#FFFFFF; font-size:38px;", transform: "matrix(1 0 0 1 81.2712 45.4452)"} 0

    %g{ id: "level-counter" }
      %text{ style: "font-size:38px;", transform: "matrix(1 0 0 1 81.2712 90)"}
        %tspan LEVEL
        %tspan.highlighted{ id: "level-counter-value" } 1
        %tspan of 10

    %g{ id: "hint-trigger", class: "ui button", visibility: "hidden" }
      %g
        %polygon{ points: "35.2,150.9 46.9,150.9 36.9,157 \t\t\t", style: "fill:#F15B22;"}
        %polygon{ points: "36.9,157 46.9,150.9 46.7,155.8 \t\t\t", style: "fill:#F05023;"}
        %polygon{ points: "38.1,157.5 45.2,157.5 42.3,162.4 \t\t\t", style: "fill:#F36D21;"}
        %polygon{ points: "38.1,157.5 38.1,162 42.3,162.4 \t\t\t", style: "fill:#F15B22;"}

      %path{ d: "M35.2,147.2h11.5l0.8-7.1l7.8-6.1l2.4-13.7l-6.1-13.2l-13-3.8l-13.9,6.5l-5,13.3\r\n\t\t\tc0,0,4.2,10.5,4.3,10.8c0.1,0.3,9.1,6.1,9.1,6.1L35.2,147.2z", style: "fill:#F36D21;"}
      %polygon{ points: "38.7,103.3 41.9,121.1 51.8,107.2 \t\t", style: "fill:#F78F1E;"}
      %polygon{ points: "51.8,107.2 41.9,121.1 57.8,120.3 \t\t", style: "fill:#F6891F;"}
      %polygon{ points: "55.4,134.1 41.9,121.1 47.6,140.1 \t\t", style: "fill:#ED4524;"}
      %polygon{ points: "35.2,147.2 39.4,136.1 46.8,147.2 \t\t", style: "fill:#C43127;"}
      %polygon{ points: "46.8,147.2 47.6,140.1 39.4,136.1 \t\t", style: "fill:#D44227;"}
      %polygon{ points: "39.4,136.1 35.2,147.2 33.3,140 \t\t", style: "fill:#ED4524;"}
      %polygon{ points: "39.4,136.1 24.2,134 33.3,140 \t\t", style: "fill:#F15622;"}
      %polygon{ points: "39.4,136.1 41.9,121.1 47.6,140.1 \t\t", style: "fill:#F36D21;"}
      %polygon{ points: "19.9,123.1 41.9,121.1 39.4,136.1 \t\t", style: "fill:#F15623;"}
      %polygon{ points: "19.9,123.1 24.2,134 39.4,136.1 \t\t", style: "fill:#E75625;"}
      %polygon{ points: "19.9,123.1 24.9,109.9 41.9,121.1 \t\t", style: "fill:#E75625;"}

      %text{ style: "font-size:38px;", transform: "matrix(1 0 0 1 81.2712 142.5897)"} HINT

    -# %g{ id: "menu-trigger", class: "ui button" }
    -#   %text{ style: "font-size:38px;", transform: "matrix(1 0 0 1 81.2697 239.7337)"} MENU
    -#   %rect{ height: "5.5", style: "fill:#F78F1E;", width: "32.7", x: "23.8", y: "214.5"}
    -#   %rect{ height: "5.5", style: "fill:#F15623;", width: "32.7", x: "23.8", y: "223.9"}
    -#   %rect{ height: "5.5", style: "fill:#D44227;", width: "32.7", x: "23.8", y: "233.3"}

    %g{ id: "menu-trigger", class: "ui button" }
      %text{ style: "font-size:38px;", transform: "matrix(1 0 0 1 81.2697 39.7337)"} MENU
      %rect{ height: "5.5", style: "fill:#F78F1E;", width: "32.7", x: "23.8", y: "14.5"}
      %rect{ height: "5.5", style: "fill:#F15623;", width: "32.7", x: "23.8", y: "23.9"}
      %rect{ height: "5.5", style: "fill:#D44227;", width: "32.7", x: "23.8", y: "33.3"}


#won-modal.overlay.hidden
  .modal
    = inline_svg "won.min.svg"

#failed-modal.overlay.hidden
  .modal
    = inline_svg "failed.min.svg"

:javascript
  var assets = {
    intro: "#{asset_path('intro.svg')}",
    world: "#{asset_path('world.svg')}",
    hollow: "#{asset_path('hollow.svg')}",
    characters: {
      0: "#{asset_path('characters/01.svg')}",
      1: "#{asset_path('characters/02.svg')}",
      2: "#{asset_path('characters/03.svg')}",
      3: "#{asset_path('characters/04.svg')}",
      4: "#{asset_path('characters/05.svg')}",
      5: "#{asset_path('characters/06.svg')}",
      6: "#{asset_path('characters/07.svg')}",
      7: "#{asset_path('characters/08.svg')}",
      8: "#{asset_path('characters/09.svg')}",
      9: "#{asset_path('characters/10.svg')}"
    }
  }

  var game = new GameController(assets);
  game.start();

  $(document).delegate('#content', 'keydown', function(e) {
    var keyCode = e.keyCode || e.which;

    if (keyCode == 9) {
      e.preventDefault();
      var start = $(this).get(0).selectionStart;
      var end = $(this).get(0).selectionEnd;

      // set textarea value to: text before caret + tab + text after caret
      $(this).val($(this).val().substring(0, start)
                  + "\t"
                  + $(this).val().substring(end));

      // put caret at right position again
      $(this).get(0).selectionStart =
      $(this).get(0).selectionEnd = start + 1;
    }
  });

app/views/menu/show.html.haml
= embedded_svg "home.svg"

- if @current_level.present? && @current_level > 1
  :javascript
    $('g#continue').on('click', function() {
      window.location.href = '/game#' + #{@current_level - 1};
    });
- else
  :javascript
    $('g#continue').remove();
:javascript
  $('g#newgame').on('click', function() {
    window.location.href = '/game';
  });

  $('g#jobs').on('click', function() {
    window.location.href = 'http://codesthq.com/jobs.html';
  });

  $('g#credits').on('click', function() {
    window.location.href = '/credits';
  });

  $('g.button').on('mouseenter mouseleave', function(e) {
    if (e.type === 'mouseenter') {
      $(this).attr('class', 'button hover');
    } else {
      $(this).attr('class', 'button');
    }

  });

app/views/summary/show.html.haml
= embedded_svg "outro.svg"

:javascript
  var message = '#{j(@message) if @message.present?}'

  if (message) {
    alert(message);
  }

  var success = '#{j(@show_success.to_s) if @show_success.present?}';

  if (success) {
    var html = "<h2>Thank you for your submission!</h2>"
    $('.victory-submition-wrap').html(html);
  }

  $(document).ready( function() {
      $('#email_form').attr('action', '#{summary_path}');
      $('#email_form').attr('method', 'post');
      $('#email_form').prepend("<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>")
    }
  );
  $('g#back').on('click', function() {
    window.location.href = '/';
  });

  $('g#fb').on('click', function() {
    fbShare('http://play.codesthq.com/', 'Fb Share', "Yay! I've finished Ruby game!", 'http://goo.gl/dS52U', 520, 350);
  });

  $('g#tw').on('click', function () {
    twitterShare('http://play.codesthq.com/', "Yay! I've finished Ruby game!");
  });

  function fbShare(url, title, descr, image, winWidth, winHeight) {
    var winTop = (screen.height / 2) - (winHeight / 2);
    var winLeft = (screen.width / 2) - (winWidth / 2);
    window.open('http://www.facebook.com/sharer.php?s=100&p[title]=' + title + '&p[summary]=' + descr + '&p[url]=' + url + '&p[images][0]=' + image, 'sharer', 'top=' + winTop + ',left=' + winLeft + ',toolbar=0,status=0,width=' + winWidth + ',height=' + winHeight);
  }

  function twitterShare(url, title) {
    window.open('http://twitter.com/share?url=' + url + '&text=' + title + '&', 'twitterwindow', 'height=450, width=550, top='+($(window).height()/2 - 225) +', left='+$(window).width()/2 +', toolbar=0, location=0, menubar=0, directories=0, scrollbars=0');
  }